### ISSUE TITLE
I can't do the module: "configuring typescript in a react application"

### ISSUE THREAD

**Issue by ediCarlosIhs** [mwarger/globomantics-react-ts#39]
I am trying to do as you in: "configuring an existing reactapp to use typescript".

I have already run: yarn install-deps. But there are so many dependencies errors. Just put here, but I have installed so many already:

yarn start

> globomantics-react@0.1.0 start
> react-scripts start

> graphqlapi@1.0.0 start
> nodemon index.js --ignore 'data'

C:\Users\edi_c\OneDrive\Documentos\Projetos\globomantics-react-ts\.pnp.cjs:12227
      Error.captureStackTrace(firstError);
            ^

Error: Your application tried to access pstree.remy, but it isn't declared in your dependencies; this makes the require call ambiguous and unsound.

Required package: pstree.remy
Required by: C:\Users\edi_c\OneDrive\Documentos\Projetos\globomantics-react-ts\api\node_modules\nodemon\lib\monitor\

Require stack:
- C:\Users\edi_c\OneDrive\Documentos\Projetos\globomantics-react-ts\api\node_modules\nodemon\lib\monitor\run.js
- C:\Users\edi_c\OneDrive\Documentos\Projetos\globomantics-react-ts\api\node_modules\nodemon\lib\monitor\index.js
- C:\Users\edi_c\OneDrive\Documentos\Projetos\globomantics-react-ts\api\node_modules\nodemon\lib\nodemon.js  
- C:\Users\edi_c\OneDrive\Documentos\Projetos\globomantics-react-ts\api\node_modules\nodemon\lib\index.js    
- C:\Users\edi_c\OneDrive\Documentos\Projetos\globomantics-react-ts\api\node_modules\nodemon\bin\nodemon.js  
    at Function.require$$0.Module._resolveFilename (C:\Users\edi_c\OneDrive\Documentos\Projetos\globomantics-react-ts\.pnp.cjs:12227:13)
    at Function.require$$0.Module._load (C:\Users\edi_c\OneDrive\Documentos\Projetos\globomantics-react-ts\.pnp.cjs:12077:42)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (C:\Users\edi_c\OneDrive\Documentos\Projetos\globomantics-react-ts\api\node_modules\nodemon\lib\monitor\run.js:15:14)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Object.require$$0.Module._extensions..js (C:\Users\edi_c\OneDrive\Documentos\Projetos\globomantics-react-ts\.pnp.cjs:12271:33)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.require$$0.Module._load (C:\Users\edi_c\OneDrive\Documentos\Projetos\globomantics-react-ts\.pnp.cjs:12108:14)
C:\Users\edi_c\OneDrive\Documentos\Projetos\globomantics-react-ts\app\node_modules\react-scripts\config\env.js:43
    require('dotenv-expand')(
                            ^

TypeError: require(...) is not a function
    at C:\Users\edi_c\OneDrive\Documentos\Projetos\globomantics-react-ts\app\node_modules\react-scripts\config\env.js:43:29
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (C:\Users\edi_c\OneDrive\Documentos\Projetos\globomantics-react-ts\app\node_modules\react-scripts\config\env.js:41:13)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Object.require$$0.Module._extensions..js (C:\Users\edi_c\OneDrive\Documentos\Projetos\globomantics-react-ts\.pnp.cjs:12271:33)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.require$$0.Module._load (C:\Users\edi_c\OneDrive\Documentos\Projetos\globomantics-react-ts\.pnp.cjs:12108:14)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
ERROR: "api" exited with 1.

**Comment by ediCarlosIhs** [comment]
I did what Stefan told to me in the course's forum.
I used npm insted of yarn and worked for me. I changed the script in package.json to run with npm:
```
cd api && npm install && cd .. && cd app && npm install && cd .. && npm install
```
my node and npm version is:
node -v && npm -v
v16.13.0
8.1.0
